# Generated by Django 3.1.7 on 2021-03-10 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название мультика')),
                ('episodes', models.TextField(verbose_name='Количество эпизодов')),
                ('status', models.TextField(verbose_name='Вышло или нет')),
                ('description', models.TextField(verbose_name='Описаное')),
            ],
            options={
                'verbose_name': 'Мультфильм',
                'verbose_name_plural': 'Мультфильмы',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_serie', models.TextField(verbose_name='Название серии')),
                ('href', models.TextField(verbose_name='Ссылка на серию')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mult.mult')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
    ]
