# Generated by Django 3.1.7 on 2021-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mult',
            name='img',
            field=models.TextField(default='https://dere.shikimori.one/system/animes/original/5114.jpg?1594817874', verbose_name='Постер'),
            preserve_default=False,
        ),
    ]
