# Generated by Django 3.1.7 on 2021-03-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0002_mult_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mult',
            options={'ordering': ['name'], 'verbose_name': 'Мультфильм', 'verbose_name_plural': 'Мультфильмы'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name_serie'], 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AddField(
            model_name='mult',
            name='genre',
            field=models.TextField(default='Экшен', verbose_name='Жанры'),
        ),
    ]
