# Generated by Django 3.1.7 on 2021-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0003_auto_20210311_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='mult',
            name='unformated_name',
            field=models.TextField(default='minihp.dom', verbose_name='Имя папки'),
            preserve_default=False,
        ),
    ]
