# Generated by Django 3.1.7 on 2021-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0004_mult_unformated_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['name'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default='США', max_length=50, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default='НЕТУ', verbose_name='Описаное'),
        ),
        migrations.AddField(
            model_name='film',
            name='filmtype',
            field=models.CharField(default='Фильм', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(default='https://kalitva-posuda.ru/upload/iblock/a3a/2.jpg', upload_to='images/films'),
        ),
        migrations.AddField(
            model_name='film',
            name='name',
            field=models.TextField(default='Название', verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='seasons',
            field=models.CharField(default='1', max_length=50, verbose_name='Количество сезонов'),
        ),
        migrations.AddField(
            model_name='film',
            name='unformated_name',
            field=models.TextField(default=models.TextField(default='Название', verbose_name='Название фильма'), verbose_name='Имя папки'),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.CharField(default='2020', max_length=10, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='mult',
            name='img',
            field=models.ImageField(upload_to='images/mults'),
        ),
    ]
