# Generated by Django 3.1.7 on 2021-03-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0006_seriesfilms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.TextField(default='https://kalitva-posuda.ru/upload/iblock/a3a/2.jpg'),
        ),
        migrations.AlterField(
            model_name='mult',
            name='img',
            field=models.TextField(verbose_name='Картинка'),
        ),
    ]
