# Generated by Django 3.1.7 on 2021-03-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0007_auto_20210321_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name_serie'], 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии Мультфильмов'},
        ),
        migrations.AlterModelOptions(
            name='seriesfilms',
            options={'ordering': ['name_serie'], 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии Фильмов'},
        ),
    ]
